### ISSUE TITLE
Explain what the stubs do

### ISSUE THREAD

**Issue by beberlei** [weirdan/doctrine-psalm-plugin#53]
I added this plugin to my large project using Doctrine and it only added two new issues. I am wondering how the stubs work, do i need to do something myself to benefit from the plugin?

I would appreciate some more docs on the features

**Comment by weirdan** [comment]
Admittedly this plugin was more useful with older versions of Doctrine that didn't have Collection annotated as generics. Running Psalm on a codebase that used Collections was a huge pain that this plugin was able to mostly eliminate. Nowadays `doctrine/collections` ships generic annotations right in its source code. 

Still there are bits and pieces that I believe still missing from Doctrine annotations. But it was a long time since I last checked, and situation may have improved since. To measure this, I've just run the test suite with the plugin disabled and got 66 failures out of 110 tests. Take a look at the [test suite](https://github.com/weirdan/doctrine-psalm-plugin/tree/master/tests/acceptance), it's very easy to read. 

Also the more strict your Psalm config (`totallyTyped=true` is strongly recommended), the more useful it gets, as it provides types that are missing in various parts of Doctrine. If you run Psalm at lower levels many of the `Mixed*` issues are suppressed, so you don't see them corrected.

**Comment by beberlei** [comment]
@weirdan thank you for clarifying, we are not using totallyTyped as the code base is still gradually moving towards static code analysis. And also we only use collections for very few things, so it makes sense we don't get errors based on that.

**Comment by beberlei** [comment]
@weirdan one question, what is the best way to annotate the attributes with collcetions to get the most out of it. I use the following now:

```php
/** 
 * @var \Doctrine\Common\Collections\Collection<array-key, PartnerInvoiceReceipt>
 */
```

**Comment by weirdan** [comment]
Yeah, that's the way. You may also use local class name (`Collection<array-key, PartnerInvoiceReceipt>`) if `Collection` is imported with `use`. I think collections as returned by doctrine are usually indexed by `int`, so `Collection<int, PartnerInvoiceReceipt>` might be a little bit more precise.
